### ISSUE TITLE
Pick a few SPEDAS capabilities and see how well ChatGPT-4 does at translating them to Python.

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#102]
We have a few open tasks that involve migrating SPEDAS features to Python:

- [ ] Moments calculations: https://github.com/spedas/pyspedas/issues/548
- [ ] L-shell calculations: https://github.com/spedas/pyspedas/issues/481
- [ ] Trace to ionosphere/equator: https://github.com/spedas/pyspedas/issues/480
- [ ] THEMIS SST calibrations: https://github.com/spedas/pyspedas/issues/432
- [ ] Displacement options to 2D slices: https://github.com/spedas/pyspedas/issues/430
- [ ] DMPA<->GSE transforms: https://github.com/spedas/pyspedas/issues/425
- [ ] Contours to 2D slices with geometric interpolation: https://github.com/spedas/pyspedas/issues/423
- [ ] B-field and S/C ram direction to MMS PGS routines:  https://github.com/spedas/pyspedas/issues/422
- [ ] PERP_SUBTRACT_BULK funtionality to 2D slices: https://github.com/spedas/pyspedas/issues/418
- [ ] Add vector projections to 2D slices: https://github.com/spedas/pyspedas/issues/417

**Comment by xandrd** [comment]
I can try to work on this https://github.com/spedas/pyspedas/issues/481 using ChatGPT.

**Comment by jameswilburlewis** [comment]
We've had very mixed results with this.  ChatGPT can be very helpful translating small pieces of code, if carefully prompted, but for larger tasks it tends to hallucinate nonexistent Python routines, and once it goes off the rails it can be very difficult to get it back on track.    The tasks mentioned in the comments above are probably beyond its ability to come up with something workable with a one-shot prompt.   Perhaps this will change as the models evolve.   So it's useful, but not yet at this high a level.
